spring:
  mail:
    host: smtp.qq.com
    username: 345744621@qq.com
    #注意:需要邮箱开通授权码服务填入下面
    password: twahybfscytucagc
    default-encoding: UTF-8
  servlet:
    multipart:
      # 启用
      enabled: true
      # 上传文件单个限制
      max-file-size: 15MB
      # 总限制
      max-request-size: 15MB
  #      # 文件上传路径
  #      location: E:/picture
  #      file-size-threshold: 0
  messages: #国际化语言
    basename: classpath:./msg/msg
    encoding: UTF-8
    cache-duration: 3600
  application:
    name: lnmj-store
  redis:
    host: localhost
    port: 6379
    password: panlin123456
    database: 5
    timeout: 10000
    charset: GBK
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.0.10:3306/lnmj_product?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true
    #username: root
    #password: root
    url: jdbc:mysql://47.108.29.183:3306/lnmj_store?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: lnmj123456
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      initialSize: 5
      minIdle: 5
      maxActive: 500
      # 配置获取连接等待超时的时间
      maxWait: 6000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      filter:
        stat:
          logSlowSql: true
      #开启游标检查  mysql不适用
      poolPreparedStatements: false
      #poolPreparedStatements 为true 生效
      maxPoolPreparedStatementPerConnectionSize: 20
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  # mybatis的model所在的包
  type-aliases-package: com.lnmj.core.bean,com.lnmj.store.entity
  #开启驼峰转换
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #打印mybatiesSql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true
logging:
  config: classpath:log4j2.yml
AOP_POINTCUT_EXPRESSION: 'execution(* *..*.service..*.*(..))'
eureka:
  instance:
    ip-address: 47.108.29.183
    prefer-ip-address: true
  client:
    register-with-eureka: true #暂时停止注册服务
    fetch-registry: true #暂时停止注册服务
    service-url:
      defaultZone: http://47.108.29.183:81/eureka/ #需要将服务注册到那个注册中心（地址）去
server:
  port: 86  #自身服务端口
oauth2:
  storeType: jwt
  user:
    client-id: user-service
    client-secret: 123456
  key:
    priKeyPath: classpath:pri.key
    pubKeyPath: classpath:pub.key
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000
  eureka:
    enabled: true
permitAll:
  url: "/productCookieCart/insertProductToCookieCart/{productId},/productCookieCart/deleteByProductIdCookie/{productId},/productCookieCart/deleteAllCookie,/productCookieCart/getCookieCart"
#  url: "/manager/store/selectStoreList,/productCookieCart/insertProductToCookieCart/{productId}"
ftp:
  address: 47.108.29.183
  port: 21
  username: ftpUser
  password: Abc2390086
  basepase: F:\images
  imagehost: 47.108.29.183:8089
file:
  filePath: E:\files #文件导出路径