spring:
  application:
    name: auth-service
  mail:
    host: smtp.qq.com
    username: 345744621@qq.com
    #注意:需要邮箱开通授权码服务填入下面
    password: twahybfscytucagc
    default-encoding: UTF-8
  main:
      allow-bean-definition-overriding: true #遇到相同名字，是否允许覆盖注册
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.141:3306/lnmj_account?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT
    username: root
    password: root
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 500
      # 配置获取连接等待超时的时间
      maxWait: 6000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      filter:
        stat:
          logSlowSql: true
      #开启游标检查  mysql不适用
      poolPreparedStatements: false
      #poolPreparedStatements 为true 生效
      maxPoolPreparedStatementPerConnectionSize: 20
  jpa:
#    hibernate:
#      ddl-auto: update
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
server:
  port: 9999
eureka:
  instance:
    ip-address: 192.168.2.143
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.2.143:81/eureka/
oauth2:
  storeType: jwt
  key:
    priKeyPath: C:\lnmj\lnmj\pri.key
    pubKeyPath: C:\lnmj\lnmj\pub.key

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # mybatis的model所在的包
  type-aliases-package: com.lnmj.authservice.Entity
  #开启驼峰转换
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #打印mybatiesSql语句
logging:
  config: classpath:log4j2.yml